version: '2.1'

volumes:
  settings:

services:
  api:
    build:
      context: ./api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  app:
    build:
      context: ./app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:3000
    networks:
      - app_network

  browser:
    restart: always
    image: bh.cr/balenalabs/browser-aarch64
    privileged: true
    ports:
      - "5011"  # management API (optional)
      - "35173" # Chromium debugging port (optional)
    volumes:
      - 'settings:/data'
    # 環境変数の設定
    environment:
      # アプリのURLに変更
      LAUNCH_URL: "http://app"
      # KIOSKモード（0=無効、1=有効）
      KIOSK: 1
      # 自動更新（秒数、0=無効）
      AUTO_REFRESH: 0
      # ハードウェア加速（0=無効、1=有効）
      ENABLE_GPU: 1
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge