version: '2.1'

volumes:
  settings:

services:
  api:
    build:
      context: ./api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  app:
    build:
      context: ./app
    restart: always
    privileged: true
    environment:
      - DISPLAY=:0
      - VITE_API_BASE_URL=http://api:3000
      - UDEV=1
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge